(()=>{'use strict';
const APP_VERSION='1.0.0',APP_BUILD='Aug 20, 2026 12:43 PM';
const BASE='appPmxC0jXgAcGbSM';
const TABLE={items:'tbl4mPMqtgtSYJ6js',locations:'tblDoroyCsIjbgSON',suppliers:'tbllnHFt4SIpywR3E',accounts:'tblvvhL8aSot0WDXF',levels:'tblRqRNwKWSQXBw1R',moves:'tblC0GBaa2aoicb2a',essentials:'tblLs4A6ZZpsaS5Dc',purchases:'tblqdI8yhZkoYogF6',restock:'tblkGMpfJdxc31on7',settings:'tblP0I26b2HKKsKE4',activity:'tblfK816wL81UU5Rn',bugs:'tblOmQ3NXAq47SKO3'};
const F={
items:{name:'fldl1cJzyNqmcTxsH',notes:'fldrlDgEB6cg6e6Gz',id:'fldNuhWI2rhOR71XI',cat:'fldAN0YMQDgk2l3Su',brand:'fldTyiei80UNnjmGG',part:'fldZl2pgnYPj31Vjp',unit:'fldtF2tevYvf9aRPf',shelf:'fldAXwfSviUc45pRA',shopMin:'fld2kIcZE6vsZo4uu',shopTarget:'flddpWrEjUdJFPqMP',lastPrice:'fldzL1U6NVcWJx4SW',lastDate:'fldTbIwTGQEE9sbvr',active:'fldDQ2kTXJxVa5nqt'},
locations:{name:'fldhLdkUidDapWI8E',type:'fldK8e8Nuh9jBl9NY',vehicle:'fldthKul32Jqg2xyA',assigned:'fldVwXegXe0jTzjxf',active:'fld7iRPdXXAEev0I9',notes:'fldxTjtOQd86Lk9cs'},
accounts:{id:'fldt22G9dxqXfp64A',name:'fldKdqzrMNPuncBWV',email:'fldGKM8vB52w9Scj5',role:'fldTo5vR8Y80KX1HC',status:'fldQeEzPiS4ufxQBN',salt:'fldKY2grG8Vg18BFZ',hash:'fldhkZDpF44E0IfOO',created:'fldHgHMagEL7xaEB4',last:'fld4bCLeBxO2mitnw',loc:'fldwzwGqZ0NU8qUuS',notes:'fldigjNiwVDKQOM1P',developer:'fldcJ9tsKp74cnmpa'},
levels:{id:'fldiRODSvkb0LrUxo',item:'fldv3HJ9oZWqI3WKY',loc:'fldeYsyKo1N4DDEpq',qty:'fldfsCsDsLJ4R7q2p',min:'fldXcINaxaquVmcyA',target:'fld4LC6SnGFCMDbwm',updated:'fldktx0LMJH9dsAXr',by:'fldXuJnEFWGKy9ndk',counted:'fldO5ZUw9r4EVjnWu',notes:'fld1dGzIsqIN7wjFL'},
moves:{id:'fld6s8HHenSCOEXLb',at:'fldTTYbkgyfXu2zkj',type:'fld0erLkMVjhOyJh7',item:'fldEdEtqJv9AoTHJV',qty:'fld7etVw3abKDvQzy',from:'fldPop5hSppAjwQQl',to:'fldK7q4Ox26DOVt2v',actor:'fldcmfULiRjb6DLVc',email:'fldZYgJtA0eL5VNbq',reason:'fldTc0HKsvDJiDY0J',cost:'fldeBJNOVEySgWoSX',notes:'fldMUlcr7o2etADCU',device:'fldfSUKmZI35EVU8P'},
ess:{id:'fld2z8SB1afa12FKg',truck:'fldVxNE6mXLL7lIXh',item:'fldVuwIvkIAjYS9Om',min:'fldSGZ5BxTcZXLDDF',target:'fldxZZ7rzw1gqegu5',active:'fldAAo4N1JTKyuznZ',notes:'fldOvOXk20OipRZup'},
purchases:{id:'fldlCuW0h9RgnnhAu',date:'fldrz0odCKmj59zwS',item:'fldf8rJyqpn0HLFlX',supplier:'fld59lKJGKDshdYTC',qty:'fldr2MW6sjKttxywq',price:'fldqiVcBWw5D3FIX4',prev:'fldjRlF9xiNbzr1V4',invoice:'fld26wWrBdbtsLDuN',into:'fldynAg1N3Yh96klB',by:'fld4KFzYLmX16dK3n',notes:'flde5hs3rx1r5rXBD'},
restock:{id:'fld6TzJ9gIxPBjQKY',created:'fldrF1uqUpqTpqjkd',loc:'fldgi2OiJQDLfyMcg',item:'fldwpg2h9IvgOwB4Q',qty:'fldO9GFg2aLWtgqUL',reason:'fldTxgKFKmX0lDRYT',status:'fldIWLpZG30XQAdok',priority:'fldq1XmAcCjEspkGh',by:'fldmu0IlPVnPRaJnZ',updated:'fldcq0GSe44QUMbRQ',notes:'fldXNCEOCRPiv7O4M'},
settings:{key:'fldI5RXkGdZUGbnj9',value:'fldGkgvOs7cOTG5LG',updated:'fldQPS3Ibb1GfnUvc',by:'fldfQbSs8odHCNwph',notes:'fldyaejkVx0ZXDitE'},
bugs:{code:'fldmYFlqXfuPOTRL9',at:'fld18jj7bPvXrgk8j',cat:'fldio3p7XCB366kSK',version:'fld5k6JaYFcpEmdwi',action:'fldA9tMj4Ot82KNhY',msg:'fldFBLVvgL1krZClE',notes:'fldIiqcLiNIol2evz',item:'fldbHBj1aVEomD5SJ',loc:'fldJWW8r3Dq3pgoiz',employee:'fldYb06EK3WrnngMs',device:'fldDkIxSdUlwtZvvg',status:'fldk93hNg2mO6DoZC',classification:'fldchJ96a3VQCiC1F',event:'fldJUxivR5NeXd2wv',userEmail:'fld7IFGZsRGlCI3Fr',session:'fldaMPK6PpZAVzKs0',control:'fldxOo33DgXSuN5FT',repeat:'fldCLAVamRvWurGdC',ux:'fldamFJAF16XmsgjU'}
};
const K={token:'rescom_inventory_airtable_pat',user:'rescom_inventory_current_user_v1',snapshot:'rescom_inventory_snapshot_v1',session:'rescom_inventory_session_id_v1'};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let DATA={items:[],locations:[],levels:[],moves:[],essentials:[],restock:[],purchases:[],accounts:[]};
let currentScreen='dashboard';
function token(){return localStorage.getItem(K.token)||''}function user(){try{return JSON.parse(localStorage.getItem(K.user)||'null')}catch{return null}}function saveUser(u){localStorage.setItem(K.user,JSON.stringify(u))}function clearUser(){localStorage.removeItem(K.user)}
function sessionId(){let x=sessionStorage.getItem(K.session);if(!x){x='INV-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);sessionStorage.setItem(K.session,x)}return x}
function device(){return navigator.userAgent+' | online='+navigator.onLine+' | '+screen.width+'x'+screen.height}
function isDev(u=user()){return !!u?.developerAccess}function isAdmin(u=user()){return !!u&&(u.role==='Owner'||u.role==='Admin'||u.developerAccess)}
function status(t){$('cloudStatus').textContent=t;$('cloudStatus').className='badge '+(navigator.onLine?'good':'warn')}
async function api(table,path='',opt={}){if(!token())throw new Error('This device is not connected to Res-Com Inventory Cloud.');const url='https://api.airtable.com/v0/'+BASE+'/'+table+(path||'');const r=await fetch(url,{...opt,headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json',...(opt.headers||{})},cache:'no-store'});if(!r.ok){const tx=await r.text();throw new Error('Airtable '+r.status+': '+tx.slice(0,500))}return r.json()}
async function all(table){let out=[],offset='';do{const q='?pageSize=100'+(offset?'&offset='+encodeURIComponent(offset):'');const d=await api(table,q);out.push(...(d.records||[]));offset=d.offset||''}while(offset);return out}
function val(f,id,name){return f[id]!==undefined?f[id]:f[name]}
function links(v){return Array.isArray(v)?v.map(x=>typeof x==='string'?x:x?.id).filter(Boolean):[]}
function account(r){const f=r.fields||{};return{recordId:r.id,accountId:val(f,F.accounts.id,'Account ID')||'',name:val(f,F.accounts.name,'Account Name')||'',email:String(val(f,F.accounts.email,'Email')||'').toLowerCase(),role:(val(f,F.accounts.role,'Role')?.name||val(f,F.accounts.role,'Role')||'Employee'),status:(val(f,F.accounts.status,'Status')?.name||val(f,F.accounts.status,'Status')||'Active'),salt:val(f,F.accounts.salt,'PIN Salt')||'',hash:val(f,F.accounts.hash,'PIN Hash')||'',developerAccess:!!val(f,F.accounts.developer,'Developer Access')}}
async function hashPin(pin,salt){const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(pin),'PBKDF2',false,['deriveBits']);const bytes=new Uint8Array((salt.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytes,iterations:120000},key,256);return [...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function salt(){return [...crypto.getRandomValues(new Uint8Array(16))].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function findAccount(email){const e=String(email||'').trim().toLowerCase();return (await all(TABLE.accounts)).map(account).find(a=>a.email===e)||null}
async function setAccountPin(acct,pin){if(!/^\d{6}$/.test(pin))throw new Error('Choose exactly 6 digits.');const s=salt(),h=await hashPin(pin,s);await api(TABLE.accounts,'',{method:'PATCH',body:JSON.stringify({records:[{id:acct.recordId,fields:{[F.accounts.salt]:s,[F.accounts.hash]:h}}],typecast:true})});acct.salt=s;acct.hash=h;return acct}
async function login(email,pin){const a=await findAccount(email);if(!a){await diag('User Mistake','login_unknown_email','No active Inventory account found for entered email','SIGN IN','Login');throw new Error('No Res-Com Inventory account was found for that email.')}if(a.status!=='Active')throw new Error('This Inventory account is disabled.');if(!a.hash){throw new Error('This account does not have a PIN yet. Use SET FIRST PIN.')}const ok=(await hashPin(pin,a.salt))===a.hash;if(!ok){await diag('User Mistake','login_wrong_pin','Incorrect personal PIN','SIGN IN','Login');throw new Error('Incorrect 6-digit personal PIN.')}saveUser(a);try{await api(TABLE.accounts,'',{method:'PATCH',body:JSON.stringify({records:[{id:a.recordId,fields:{[F.accounts.last]:new Date().toISOString()}}]})})}catch{}await diag('Success','login_success','Employee signed in','SIGN IN','Login');return a}
async function diag(cls,key,msg,control='',cat='Other',notes=''){try{const u=user(),fields={[F.bugs.code]:'INV-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),[F.bugs.at]:new Date().toISOString(),[F.bugs.cat]:cat,[F.bugs.version]:APP_VERSION,[F.bugs.action]:currentScreen,[F.bugs.msg]:String(msg).slice(0,3900),[F.bugs.notes]:String(notes).slice(0,3900),[F.bugs.employee]:u?.name||'',[F.bugs.device]:device(),[F.bugs.status]:'New',[F.bugs.classification]:cls,[F.bugs.event]:key,[F.bugs.userEmail]:u?.email||null,[F.bugs.session]:sessionId(),[F.bugs.control]:String(control).slice(0,400)};if(token()&&navigator.onLine)await api(TABLE.bugs,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})})}catch{}}
window.addEventListener('error',e=>diag('Bug','window_error',e.message||'JavaScript error','window','Other'));window.addEventListener('unhandledrejection',e=>diag('Bug','promise_rejection',String(e.reason?.message||e.reason||'Unhandled rejection'),'promise','Other'));
async function setting(key){const rows=await all(TABLE.settings);const r=rows.find(x=>(x.fields?.['Setting Key']||x.fields?.[F.settings.key])===key);return r?{id:r.id,value:r.fields?.['Setting Value']??r.fields?.[F.settings.value]??''}:null}
async function setSetting(key,value){const s=await setting(key),fields={[F.settings.key]:key,[F.settings.value]:String(value),[F.settings.updated]:new Date().toISOString(),[F.settings.by]:user()?.email||null};if(s)return api(TABLE.settings,'',{method:'PATCH',body:JSON.stringify({records:[{id:s.id,fields}],typecast:true})});return api(TABLE.settings,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})})}
function gate(html){$('gate').innerHTML='<div class="gateCard">'+html+'</div>';$('gate').classList.remove('hidden')}
function gateMsg(t){const e=$('gateMsg');if(e)e.textContent=t}
function showConnect(msg=''){gate(`<img class="gateLogo" src="icon-192.png"><h2>Connect Res-Com Inventory</h2><p>This is a private company app. Connect this device to the Res-Com Airtable cloud once.</p><label>Res-Com Cloud Token</label><input id="cloudToken" type="password" autocomplete="off" placeholder="pat…"><button class="primary" id="connectBtn">CONNECT THIS DEVICE</button><div class="msg" id="gateMsg">${esc(msg)}</div><p class="small">The token stays on this device. Do not send it in text messages or put it in GitHub.</p>`);$('connectBtn').onclick=async()=>{const t=$('cloudToken').value.trim();if(!t)return gateMsg('Enter the restricted Airtable token.');localStorage.setItem(K.token,t);try{await all(TABLE.accounts);showLogin('Cloud connected. Sign in.')}catch(e){localStorage.removeItem(K.token);gateMsg('Connection failed. '+e.message)}}}
function showLogin(msg=''){gate(`<img class="gateLogo" src="icon-192.png"><h2>Res-Com Inventory</h2><p>Approved Res-Com employees only.</p><label>Email</label><input id="loginEmail" type="email" autocomplete="username"><label>6-Digit Personal PIN</label><input id="loginPin" inputmode="numeric" maxlength="6" type="password"><button class="primary" id="loginBtn">SIGN IN</button><button class="outline" id="firstPinBtn">SET FIRST PIN</button><button class="gray" id="disconnectBtn">DISCONNECT CLOUD FROM THIS DEVICE</button><div class="msg" id="gateMsg">${esc(msg)}</div>`);$('loginBtn').onclick=async()=>{try{await login($('loginEmail').value,$('loginPin').value);$('gate').classList.add('hidden');await start()}catch(e){gateMsg(e.message)}};$('firstPinBtn').onclick=()=>showFirstPin();$('disconnectBtn').onclick=()=>{localStorage.removeItem(K.token);clearUser();showConnect('Cloud connection removed from this device.')}}
function showFirstPin(){gate(`<img class="gateLogo" src="icon-192.png"><h2>Set Your First PIN</h2><p>For the initial setup, this is available only to a Developer account that does not have a PIN yet.</p><label>Developer Email</label><input id="firstEmail" type="email"><label>New 6-Digit PIN</label><input id="firstPin" inputmode="numeric" maxlength="6" type="password"><label>Confirm PIN</label><input id="firstPin2" inputmode="numeric" maxlength="6" type="password"><button class="primary" id="saveFirstPin">SAVE MY PIN</button><button class="gray" id="backLogin">BACK</button><div class="msg" id="gateMsg"></div>`);$('backLogin').onclick=()=>showLogin();$('saveFirstPin').onclick=async()=>{try{const email=$('firstEmail').value.trim().toLowerCase(),p=$('firstPin').value,p2=$('firstPin2').value;if(p!==p2)throw new Error('PINs do not match.');const a=await findAccount(email);if(!a)throw new Error('Developer account not found.');if(!a.developerAccess)throw new Error('First-PIN setup is restricted to Developer accounts.');if(a.hash)throw new Error('This account already has a PIN.');await setAccountPin(a,p);saveUser(a);$('gate').classList.add('hidden');await start()}catch(e){gateMsg(e.message)}}}
function logout(){clearUser();showLogin('Signed out.')}
async function refresh(){status('SYNCING…');const [items,locations,levels,moves,essentials,restock,purchases,accounts]=await Promise.all([all(TABLE.items),all(TABLE.locations),all(TABLE.levels),all(TABLE.moves),all(TABLE.essentials),all(TABLE.restock),all(TABLE.purchases),all(TABLE.accounts)]);DATA={items,locations,levels,moves,essentials,restock,purchases,accounts};localStorage.setItem(K.snapshot,JSON.stringify(DATA));status('CLOUD LIVE');renderAll()}
function loadSnapshot(){try{const d=JSON.parse(localStorage.getItem(K.snapshot)||'null');if(d)DATA=d}catch{}}
const byId=(arr,id)=>arr.find(x=>x.id===id);function itemName(id){const r=byId(DATA.items,id);return r?.fields?.['Item Name']||r?.fields?.[F.items.name]||'Unknown Item'}function locName(id){const r=byId(DATA.locations,id);return r?.fields?.['Location Name']||r?.fields?.[F.locations.name]||'Unknown Location'}
function itemActive(r){const v=r.fields?.['Active']??r.fields?.[F.items.active];return v!==false}function locActive(r){const v=r.fields?.['Active']??r.fields?.[F.locations.active];return v!==false}
function levelFor(itemId,locId){return DATA.levels.find(r=>links(r.fields?.['Item']??r.fields?.[F.levels.item]).includes(itemId)&&links(r.fields?.['Location']??r.fields?.[F.levels.loc]).includes(locId))}
function qty(itemId,locId){return Number(levelFor(itemId,locId)?.fields?.['Qty On Hand']??levelFor(itemId,locId)?.fields?.[F.levels.qty]??0)}
function optionsItems(){return DATA.items.filter(itemActive).map(r=>`<option value="${r.id}">${esc(itemName(r.id))}</option>`).join('')}function optionsLocs(type=''){return DATA.locations.filter(r=>locActive(r)&&(!type||((r.fields?.['Location Type']?.name||r.fields?.['Location Type']||'')===type))).map(r=>`<option value="${r.id}">${esc(locName(r.id))}</option>`).join('')}
function screen(id){document.querySelectorAll('main section').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');currentScreen=id;document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));window.scrollTo(0,0);diag('Navigation','screen_'+id,'Opened '+id,id,'Navigation')}
function renderDashboard(){const shop=DATA.locations.find(r=>(r.fields?.['Location Type']?.name||r.fields?.['Location Type'])==='Shop');let low=0,totalQty=0;if(shop){for(const i of DATA.items.filter(itemActive)){const q=qty(i.id,shop.id),min=Number(i.fields?.['Shop Minimum Qty']??i.fields?.[F.items.shopMin]??0);totalQty+=q;if(min&&q<min)low++}}const trucks=DATA.locations.filter(r=>(r.fields?.['Location Type']?.name||r.fields?.['Location Type'])==='Truck'&&locActive(r)).length;const openRestock=DATA.restock.filter(r=>{const s=r.fields?.['Status']?.name||r.fields?.['Status'];return !['Received','Dismissed'].includes(s)}).length;$('stats').innerHTML=`<div class="stat"><span class="small">SHOP UNITS ON HAND</span><b>${totalQty}</b></div><div class="stat"><span class="small">LOW SHOP ITEMS</span><b>${low}</b></div><div class="stat"><span class="small">ACTIVE TRUCKS</span><b>${trucks}</b></div><div class="stat"><span class="small">RESTOCK REQUESTS</span><b>${openRestock}</b></div>`;const rec=[...DATA.moves].sort((a,b)=>Date.parse(b.fields?.['Occurred At']||0)-Date.parse(a.fields?.['Occurred At']||0)).slice(0,10);$('recentMoves').innerHTML=rec.length?rec.map(r=>{const f=r.fields,t=f['Movement Type']?.name||f['Movement Type']||'',iid=links(f['Item']||f[F.moves.item])[0],from=links(f['From Location']||f[F.moves.from])[0],to=links(f['To Location']||f[F.moves.to])[0];return `<div class="row"><div class="grow"><h3>${esc(itemName(iid))}</h3><p>${esc(t)} • ${esc(from?locName(from):'—')} → ${esc(to?locName(to):'—')} • ${esc(f['Actor Name']||'')}</p></div><div class="qty">${Number(f['Quantity']||0)}</div></div>`}).join(''):'<div class="listEmpty">No inventory movement yet.</div>'}
function renderShop(){const shop=DATA.locations.find(r=>(r.fields?.['Location Type']?.name||r.fields?.['Location Type'])==='Shop');const q=String($('shopSearch')?.value||'').toLowerCase();let rows=DATA.items.filter(itemActive).filter(r=>!q||itemName(r.id).toLowerCase().includes(q)||String(r.fields?.['Part Number']||'').toLowerCase().includes(q));$('shopList').innerHTML=shop?rows.map(r=>{const on=qty(r.id,shop.id),min=Number(r.fields?.['Shop Minimum Qty']??0),target=Number(r.fields?.['Shop Target Qty']??0),need=Math.max(0,target-on),low=min&&on<min;return `<div class="row"><div class="grow"><h3>${esc(itemName(r.id))}</h3><p>${esc(r.fields?.['Category']||'')} ${r.fields?.['Part Number']?'• '+esc(r.fields['Part Number']):''} ${r.fields?.['Shop Shelf / Bin']?'• '+esc(r.fields['Shop Shelf / Bin']):''}</p>${low?`<span class="badge warn">RESTOCK ${need||Math.max(0,min-on)}</span>`:''}</div><div class="qty">${on}</div></div>`}).join(''):'<div class="listEmpty">Res-Com Shop location not found.</div>'}
function renderTrucks(){const trucks=DATA.locations.filter(r=>locActive(r)&&((r.fields?.['Location Type']?.name||r.fields?.['Location Type'])==='Truck'));$('truckList').innerHTML=trucks.length?trucks.map(t=>{const levels=DATA.levels.filter(l=>links(l.fields?.['Location']||l.fields?.[F.levels.loc]).includes(t.id)&&Number(l.fields?.['Qty On Hand']??0)>0),ess=DATA.essentials.filter(e=>links(e.fields?.['Truck']||e.fields?.[F.ess.truck]).includes(t.id)&&(e.fields?.['Active']??true)!==false);let needs=0;for(const e of ess){const iid=links(e.fields?.['Item']||e.fields?.[F.ess.item])[0],target=Number(e.fields?.['Target Qty']??0);if(qty(iid,t.id)<target)needs++}return `<div class="card"><div class="sectionTitle"><div><h3>${esc(locName(t.id))}</h3><div class="small">${esc(t.fields?.['Assigned To']||'Unassigned')} ${t.fields?.['Truck / Vehicle Number']?'• '+esc(t.fields['Truck / Vehicle Number']):''}</div></div><span class="badge ${needs?'warn':'good'}">${needs?needs+' RESTOCK':'READY'}</span></div><div class="small">${levels.length} stocked item(s)</div><button class="outline truckOpen" data-id="${t.id}">VIEW TRUCK</button></div>`}).join(''):'<div class="listEmpty">No trucks have been added yet.</div>';document.querySelectorAll('.truckOpen').forEach(b=>b.onclick=()=>openTruck(b.dataset.id))}
function openTruck(id){const t=byId(DATA.locations,id);$('truckTitle').textContent=locName(id);const levels=DATA.levels.filter(l=>links(l.fields?.['Location']||l.fields?.[F.levels.loc]).includes(id)&&Number(l.fields?.['Qty On Hand']??0)>0);const ess=DATA.essentials.filter(e=>links(e.fields?.['Truck']||e.fields?.[F.ess.truck]).includes(id)&&(e.fields?.['Active']??true)!==false);const essentialIds=new Set(ess.map(e=>links(e.fields?.['Item']||e.fields?.[F.ess.item])[0]));let html='<h3>Essentials</h3>';html+=ess.length?ess.map(e=>{const iid=links(e.fields?.['Item']||e.fields?.[F.ess.item])[0],on=qty(iid,id),target=Number(e.fields?.['Target Qty']??0),need=Math.max(0,target-on);return `<div class="row"><div class="grow"><b>${esc(itemName(iid))}</b><p>Target ${target}</p></div><div>${on}${need?` <span class="badge warn">NEED ${need}</span>`:''}</div></div>`}).join(''):'<div class="small">No essentials defined for this truck yet.</div>';html+='<h3>Misc / Added From Shop</h3>';const misc=levels.filter(l=>!essentialIds.has(links(l.fields?.['Item']||l.fields?.[F.levels.item])[0]));html+=misc.length?misc.map(l=>{const iid=links(l.fields?.['Item']||l.fields?.[F.levels.item])[0];return `<div class="row"><div class="grow"><b>${esc(itemName(iid))}</b></div><div class="qty">${Number(l.fields?.['Qty On Hand']??0)}</div></div>`}).join(''):'<div class="small">No miscellaneous stock.</div>';$('truckDetailBody').innerHTML=html;$('essentialTruck').value=id;screen('truckDetail')}
async function updateLevel(itemId,locId,newQty){let r=levelFor(itemId,locId),now=new Date().toISOString(),fields={[F.levels.qty]:newQty,[F.levels.updated]:now,[F.levels.by]:user().email};if(r){await api(TABLE.levels,'',{method:'PATCH',body:JSON.stringify({records:[{id:r.id,fields}]})});r.fields['Qty On Hand']=newQty}else{fields[F.levels.id]='IL-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase();fields[F.levels.item]=[itemId];fields[F.levels.loc]=[locId];const d=await api(TABLE.levels,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})});DATA.levels.push(d.records[0])}}
async function moveStock(){if(!navigator.onLine)throw new Error('Inventory changes require internet so quantities cannot conflict.');const type=$('moveType').value,item=$('moveItem').value,from=$('moveFrom').value,to=$('moveTo').value,q=Number($('moveQty').value),reason=$('moveReason').value.trim();if(!item||!q||q<=0)throw new Error('Choose an item and quantity.');if(type==='Received'){if(!to)throw new Error('Choose where the received stock is going.')}else if(type==='Used'||type==='Discarded'||type==='Adjustment Out'){if(!from)throw new Error('Choose the location stock is leaving.')}else if(type==='Adjustment In'){if(!to)throw new Error('Choose the location stock is entering.')}else{if(!from||!to||from===to)throw new Error('Choose two different locations.')}if(from){const have=qty(item,from);if(q>have&&type!=='Adjustment Out')throw new Error('Not enough stock at '+locName(from)+'. Current quantity: '+have);await updateLevel(item,from,Math.max(0,have-q))}if(to){await updateLevel(item,to,qty(item,to)+q)}const fields={[F.moves.id]:'MV-'+Date.now().toString(36).toUpperCase(),[F.moves.at]:new Date().toISOString(),[F.moves.type]:type,[F.moves.item]:[item],[F.moves.qty]:q,[F.moves.actor]:user().name,[F.moves.email]:user().email,[F.moves.reason]:reason,[F.moves.device]:device()};if(from)fields[F.moves.from]=[from];if(to)fields[F.moves.to]=[to];await api(TABLE.moves,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})});await diag('Success','inventory_move',type+' '+q+' '+itemName(item),$('moveSubmit').textContent,'Transfer');await refresh();$('moveMsg').textContent='✓ Inventory updated.'}
async function addItem(){if(!isAdmin())throw new Error('Admin/Developer access required.');const name=$('newItemName').value.trim();if(!name)throw new Error('Enter item name.');const fields={[F.items.name]:name,[F.items.id]:'IT-'+Date.now().toString(36).toUpperCase(),[F.items.cat]:$('newItemCat').value.trim(),[F.items.brand]:$('newItemBrand').value.trim(),[F.items.part]:$('newItemPart').value.trim(),[F.items.unit]:$('newItemUnit').value.trim()||'each',[F.items.shelf]:$('newItemShelf').value.trim(),[F.items.shopMin]:Number($('newItemMin').value||0),[F.items.shopTarget]:Number($('newItemTarget').value||0),[F.items.lastPrice]:Number($('newItemPrice').value||0),[F.items.active]:true};await api(TABLE.items,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})});await refresh();$('newItemMsg').textContent='✓ Item added.'}
async function addTruck(){if(!isAdmin())throw new Error('Admin/Developer access required.');const name=$('newTruckName').value.trim();if(!name)throw new Error('Enter truck name.');const fields={[F.locations.name]:name,[F.locations.type]:'Truck',[F.locations.vehicle]:$('newTruckNumber').value.trim(),[F.locations.assigned]:$('newTruckAssigned').value.trim(),[F.locations.active]:true};await api(TABLE.locations,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})});await refresh();$('newTruckMsg').textContent='✓ Truck added.'}
async function addEssential(){if(!isAdmin())throw new Error('Admin/Developer access required.');const truck=$('essentialTruck').value,item=$('essentialItem').value,target=Number($('essentialTarget').value);if(!truck||!item||target<=0)throw new Error('Choose truck, item and target quantity.');const fields={[F.ess.id]:'ES-'+Date.now().toString(36).toUpperCase(),[F.ess.truck]:[truck],[F.ess.item]:[item],[F.ess.min]:Math.max(0,Number($('essentialMin').value||0)),[F.ess.target]:target,[F.ess.active]:true};await api(TABLE.essentials,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})});await refresh();$('essentialMsg').textContent='✓ Essential added.'}
async function addPurchase(){if(!isAdmin())throw new Error('Admin/Developer access required.');const item=$('purchaseItem').value,into=$('purchaseInto').value,qtyN=Number($('purchaseQty').value),price=Number($('purchasePrice').value);if(!item||!into||qtyN<=0||price<0)throw new Error('Enter item, received location, quantity, and unit price.');const ir=byId(DATA.items,item),prev=Number(ir.fields?.['Last Purchase Price']??0);const today=new Date().toISOString().slice(0,10),fields={[F.purchases.id]:'PO-'+Date.now().toString(36).toUpperCase(),[F.purchases.date]:today,[F.purchases.item]:[item],[F.purchases.qty]:qtyN,[F.purchases.price]:price,[F.purchases.prev]:prev,[F.purchases.into]:[into],[F.purchases.by]:user().email,[F.purchases.invoice]:$('purchaseInvoice').value.trim(),[F.purchases.notes]:$('purchaseNotes').value.trim()};await api(TABLE.purchases,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})});await api(TABLE.items,'',{method:'PATCH',body:JSON.stringify({records:[{id:item,fields:{[F.items.lastPrice]:price,[F.items.lastDate]:today}}]})});await updateLevel(item,into,qty(item,into)+qtyN);const mv={[F.moves.id]:'MV-'+Date.now().toString(36).toUpperCase(),[F.moves.at]:new Date().toISOString(),[F.moves.type]:'Received',[F.moves.item]:[item],[F.moves.qty]:qtyN,[F.moves.to]:[into],[F.moves.actor]:user().name,[F.moves.email]:user().email,[F.moves.cost]:price,[F.moves.reason]:'Purchase received',[F.moves.device]:device()};await api(TABLE.moves,'',{method:'POST',body:JSON.stringify({records:[{fields:mv}],typecast:true})});const diff=price-prev,pct=prev?diff/prev*100:0;$('purchaseMsg').textContent=prev?`✓ Received. Previous $${prev.toFixed(2)} → $${price.toFixed(2)} (${diff>=0?'+':''}$${diff.toFixed(2)}, ${pct>=0?'+':''}${pct.toFixed(1)}%).`:`✓ First price recorded at $${price.toFixed(2)}.`;await refresh()}
function renderRestock(){let rows=[];const shop=DATA.locations.find(r=>(r.fields?.['Location Type']?.name||r.fields?.['Location Type'])==='Shop');if(shop)for(const i of DATA.items.filter(itemActive)){const on=qty(i.id,shop.id),min=Number(i.fields?.['Shop Minimum Qty']??0),target=Number(i.fields?.['Shop Target Qty']??0);if(min&&on<min)rows.push({loc:shop.id,item:i.id,on,target,need:Math.max(0,target-on),why:'Shop below minimum'})}for(const e of DATA.essentials){if((e.fields?.['Active']??true)===false)continue;const t=links(e.fields?.['Truck']||e.fields?.[F.ess.truck])[0],i=links(e.fields?.['Item']||e.fields?.[F.ess.item])[0],target=Number(e.fields?.['Target Qty']??0),on=qty(i,t);if(target&&on<target)rows.push({loc:t,item:i,on,target,need:target-on,why:'Truck essential'})}$('restockList').innerHTML=rows.length?rows.sort((a,b)=>b.need-a.need).map(x=>`<div class="row"><div class="grow"><h3>${esc(itemName(x.item))}</h3><p>${esc(locName(x.loc))} • ${esc(x.why)} • Has ${x.on}, target ${x.target}</p></div><span class="badge warn">NEED ${x.need}</span></div>`).join(''):'<div class="listEmpty">Everything is at target based on current settings.</div>'}
function renderTeam(){const me=user(),rows=DATA.accounts.map(account);$('teamMe').innerHTML=`<b>${esc(me.name)}</b><div class="small">${esc(me.email)} • ${esc(me.role)} ${me.developerAccess?'• DEVELOPER':''}</div>`;$('teamList').innerHTML=rows.map(a=>`<div class="row"><div class="grow"><h3>${esc(a.name)}</h3><p>${esc(a.email)} • ${esc(a.role)} ${a.developerAccess?'• Developer':''} • ${a.hash?'PIN SET':'PIN NOT SET'}</p></div>${isAdmin()&&a.accountId!==me.accountId?`<button class="outline setPinOther" data-id="${a.accountId}" style="width:auto">SET PIN</button>`:''}</div>`).join('');document.querySelectorAll('.setPinOther').forEach(b=>b.onclick=()=>adminSetPin(b.dataset.id));$('adminTools').classList.toggle('hidden',!isAdmin());$('releaseCenter').classList.toggle('hidden',!isDev());if(isDev())renderReleaseCenter()}
async function adminSetPin(id){const a=DATA.accounts.map(account).find(x=>x.accountId===id);if(!a)return;const p=prompt('Enter a new 6-digit PIN for '+a.name);if(p===null)return;if(!/^\d{6}$/.test(p))return alert('PIN must be exactly 6 digits.');await setAccountPin(a,p);await refresh();alert('PIN updated for '+a.name+'.')}
async function addAccount(){if(!isAdmin())throw new Error('Admin/Developer access required.');const name=$('acctName').value.trim(),email=$('acctEmail').value.trim().toLowerCase(),role=$('acctRole').value,pin=$('acctPin').value;if(!name||!/\S+@\S+\.\S+/.test(email))throw new Error('Enter name and valid email.');if(DATA.accounts.map(account).some(a=>a.email===email))throw new Error('That email already exists.');const fields={[F.accounts.id]:'INV-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),[F.accounts.name]:name,[F.accounts.email]:email,[F.accounts.role]:role,[F.accounts.status]:'Active',[F.accounts.created]:new Date().toISOString()};if(pin){if(!/^\d{6}$/.test(pin))throw new Error('PIN must be exactly 6 digits or blank.');const s=salt();fields[F.accounts.salt]=s;fields[F.accounts.hash]=await hashPin(pin,s)}await api(TABLE.accounts,'',{method:'POST',body:JSON.stringify({records:[{fields}],typecast:true})});await refresh();$('acctMsg').textContent='✓ Employee account created.'}
async function renderReleaseCenter(){let rel='1.0.0',cand='1.0.0';try{rel=(await setting('released_app_version'))?.value||rel;cand=(await setting('candidate_app_version'))?.value||cand}catch{}$('releaseInfo').innerHTML=`<b>TEAM RELEASE:</b> v${esc(rel)}<br><b>CANDIDATE:</b> v${esc(cand)}<p class="small">Uploading files does not interrupt field users. A Developer releases the candidate after testing.</p>`;$('releaseBtn').onclick=async()=>{await setSetting('released_app_version',APP_VERSION);$('releaseMsg').textContent='✓ v'+APP_VERSION+' approved for the company. Devices use it on their next normal launch.'};$('rollbackBtn').onclick=async()=>{$('releaseMsg').textContent='No older Inventory release exists yet. Rollback becomes available starting with v1.1.'}}
function populateForms(){$('moveItem').innerHTML='<option value="">Choose item…</option>'+optionsItems();$('purchaseItem').innerHTML='<option value="">Choose item…</option>'+optionsItems();$('essentialItem').innerHTML='<option value="">Choose item…</option>'+optionsItems();const locs='<option value="">Choose location…</option>'+optionsLocs();$('moveFrom').innerHTML=locs;$('moveTo').innerHTML=locs;$('purchaseInto').innerHTML=locs;$('essentialTruck').innerHTML='<option value="">Choose truck…</option>'+optionsLocs('Truck')}
function renderAll(){renderDashboard();renderShop();renderTrucks();renderRestock();populateForms();renderTeam();$('appVersion').textContent='v'+APP_VERSION}
async function start(){const u=user();if(!u)return showLogin();$('gate').classList.add('hidden');$('who').textContent=u.name+(u.developerAccess?' • Developer':'');loadSnapshot();renderAll();if(navigator.onLine){try{const live=await findAccount(u.email);if(!live||live.status!=='Active'){clearUser();return showLogin('This account is no longer active.')}saveUser(live);await refresh()}catch(e){status('OFFLINE SNAPSHOT');diag('Warning','refresh_failed',e.message,'startup','Network')}}else status('OFFLINE SNAPSHOT');screen('dashboard')}
function bind(){document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>screen(b.dataset.screen));$('refreshBtn').onclick=()=>refresh().catch(e=>alert(e.message));$('logoutBtn').onclick=logout;$('shopSearch').oninput=renderShop;$('moveSubmit').onclick=()=>moveStock().catch(e=>{$('moveMsg').textContent=e.message;diag('User Mistake','move_validation',e.message,'MOVE STOCK','Transfer')});$('addItemBtn').onclick=()=>addItem().catch(e=>$('newItemMsg').textContent=e.message);$('addTruckBtn').onclick=()=>addTruck().catch(e=>$('newTruckMsg').textContent=e.message);$('addEssentialBtn').onclick=()=>addEssential().catch(e=>$('essentialMsg').textContent=e.message);$('purchaseBtn').onclick=()=>addPurchase().catch(e=>$('purchaseMsg').textContent=e.message);$('addAccountBtn').onclick=()=>addAccount().catch(e=>$('acctMsg').textContent=e.message);$('backTrucks').onclick=()=>screen('trucks');document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;diag('Action','button_'+(b.id||b.dataset.screen||'unknown'),'Button selected: '+(b.textContent||'').trim().slice(0,100),b.id||b.dataset.screen||'button','Button')},true)}
async function boot(){bind();$('buildText').textContent='Build '+APP_BUILD;if(!token())return showConnect();if(!user())return showLogin();start()}
window.addEventListener('online',()=>{status('ONLINE');if(user())refresh().catch(()=>{})});window.addEventListener('offline',()=>status('OFFLINE SNAPSHOT'));
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js?appv='+APP_VERSION,{updateViaCache:'none'}).catch(()=>{});
boot();
})();