(()=>{'use strict';
const BASE='appPmxC0jXgAcGbSM',ITEMS='tbl4mPMqtgtSYJ6js',TOKEN_KEY='rescom_inventory_airtable_pat',USER_KEY='rescom_inventory_current_user_v1';
let loaded=false,loading=null,items=[],filtered=[],limit=120,atlasUri='';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function user(){try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}}function canSync(){const u=user();return !!u&&(u.developerAccess||u.role==='Owner'||u.role==='Admin')}
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Could not load '+src));document.head.appendChild(s)})}
async function ensureLoaded(){if(loaded)return;if(loading)return loading;loading=(async()=>{const f=window.RESCOM_DATA_FILES;if(!f)throw new Error('Inventory data file list is missing.');$('catalogStatus').textContent='Loading PDF inventory and photos…';for(const x of f.inventory)await script(x+'?v=1.1.0');for(const x of f.atlas)await script(x+'?v=1.1.0');await script(f.photoMap+'?v=1.1.0');const bin=Uint8Array.from(atob(window.__RESCOM_INV_GZ_B64||''),c=>c.charCodeAt(0));let text;if('DecompressionStream'in window){const ds=new DecompressionStream('gzip');text=await new Response(new Blob([bin]).stream().pipeThrough(ds)).text()}else throw new Error('This phone/browser is too old to open the compressed inventory. Update the browser and try again.');items=JSON.parse(text);atlasUri='data:image/jpeg;base64,'+(window.__RESCOM_ATLAS_B64||'');window.__RESCOM_INV_GZ_B64='';window.__RESCOM_ATLAS_B64='';loaded=true;buildCategories();applyFilter();$('catalogSyncCard').classList.toggle('hidden',!canSync())})();try{await loading}catch(e){$('catalogStatus').textContent='Catalog error: '+e.message;throw e}finally{loading=null}}
function buildCategories(){const cats=[...new Set(items.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b));$('catalogCategory').innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('')}
function photoStyle(key,scale=1){const m=window.RESCOM_PHOTO_MAP?.[key];if(!m||!atlasUri)return '';const [x,y,w,h,W,H]=m;return `background-image:url(${atlasUri});background-size:${W*scale}px ${H*scale}px;background-position:-${x*scale}px -${y*scale}px;width:${w*scale}px;height:${h*scale}px`}
function applyFilter(){if(!loaded)return;const q=String($('catalogSearch').value||'').trim().toLowerCase(),cat=$('catalogCategory').value;filtered=items.filter(x=>(!cat||x.category===cat)&&(!q||[x.item,x.partNumber,x.manufacturer,x.category,x.supplier,x.rawSupplier,x.location,x.notes].some(v=>String(v||'').toLowerCase().includes(q))));limit=120;render()}
function render(){const show=filtered.slice(0,limit);$('catalogStatus').textContent=`${filtered.length.toLocaleString()} matching item(s) • PDF master has ${items.length.toLocaleString()} items`;$('catalogGrid').innerHTML=show.map(x=>{const p=x.photos?.[0]||'';return `<div class="catalogItem" data-id="${esc(x.id)}"><div class="catalogThumb" style="${photoStyle(p,1)}"></div><div class="catalogText"><h3>${esc(x.item)}</h3><p>${esc(x.manufacturer||'')} ${x.partNumber?'• '+esc(x.partNumber):''}</p><p>${esc(x.category||'')} ${x.location?'• '+esc(x.location):''}</p><div class="catalogMeta">${x.price!=null?`<span class="catalogPill">$${Number(x.price).toFixed(2)}</span>`:''}${x.stockPolicy?`<span class="catalogPill">${esc(x.stockPolicy)}</span>`:''}${x.supplier?`<span class="catalogPill">${esc(x.supplier)}</span>`:''}</div></div></div>`}).join('')||'<div class="card">No matching inventory items.</div>';$('catalogMore').classList.toggle('hidden',show.length>=filtered.length)}
function openItem(id){const x=items.find(i=>i.id===id);if(!x)return;const photos=x.photos||[],p=photos[0]||'';const info=[['Item ID',x.id],['Category',x.category],['Manufacturer',x.manufacturer],['Part Number',x.partNumber],['Unit',x.unit],['Last Price',x.price!=null?'$'+Number(x.price).toFixed(2):''],['Price Date',x.priceDate],['Shop Location',x.location],['Supplier',x.supplier||x.rawSupplier],['Stock Policy',x.stockPolicy],['Shop Minimum',x.shopMinimumQty],['Shop Target',x.shopTargetQty],['PDF Page',x.sourcePage],['Source Stock Rule',x.rawStock]].filter(a=>a[1]!==null&&a[1]!==undefined&&a[1]!=='');$('catalogModalBody').innerHTML=`<h2>${esc(x.item)}</h2>${p?`<div class="catalogDetailPhoto" style="${photoStyle(p,3)}"></div>`:'<div class="note">No specific item photo was mapped; the source PDF row is still preserved.</div>'}<div class="catalogDetailGrid">${info.map(([k,v])=>`<div><b>${esc(k)}</b>${esc(v)}</div>`).join('')}</div>${x.notes?`<div class="catalogNotes"><b>NOTES</b><br>${esc(x.notes)}</div>`:''}${photos.length>1?`<div class="small" style="margin-top:8px">${photos.length} source photos mapped to this item.</div>`:''}`;$('catalogModal').classList.remove('hidden')}
async function airtable(path='',opt={}){const token=localStorage.getItem(TOKEN_KEY)||'';if(!token)throw new Error('Connect this device to Res-Com Airtable first.');const r=await fetch(`https://api.airtable.com/v0/${BASE}/${ITEMS}${path}`,{...opt,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})},cache:'no-store'});if(!r.ok)throw new Error('Airtable '+r.status+': '+((await r.text()).slice(0,300)));return r.json()}
async function existingMap(){let out=new Map(),off='';do{const d=await airtable('?pageSize=100'+(off?'&offset='+encodeURIComponent(off):''));for(const r of d.records||[]){const id=r.fields?.['Item ID'];if(id)out.set(id,r.id)}off=d.offset||''}while(off);return out}
function fields(x){const f={'Item Name':x.item,'Item ID':x.id,'Category':x.category||'','Brand / Manufacturer':x.manufacturer||'','Part Number':x.partNumber||'','Unit':x.unit||'each','Shop Shelf / Bin':x.location||'','Active':true,'Stock Policy':x.stockPolicy||'Unspecified','Raw Stock Rule':x.rawStock||'','Source Cost Text':x.rawCost||'','Source Supplier Text':x.rawSupplier||'','Source Page':x.sourcePage,'Source Row':x.sourceRow,'PDF Photo Keys':(x.photos||[]).join('\n'),'PDF Photo Count':(x.photos||[]).length};if(x.notes)f['Notes']=x.notes;if(x.shopMinimumQty!=null)f['Shop Minimum Qty']=x.shopMinimumQty;if(x.shopTargetQty!=null)f['Shop Target Qty']=x.shopTargetQty;if(x.price!=null)f['Last Purchase Price']=x.price;if(x.priceDate)f['Last Purchase Date']=x.priceDate;if(x.review)f['Import Review']=x.review;return f}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function syncAll(){if(!canSync())throw new Error('Admin/Owner/Developer access required.');await ensureLoaded();const btn=$('catalogSyncBtn'),msg=$('catalogSyncMsg');btn.disabled=true;try{msg.innerHTML='<div class="catalogProgress"><span id="syncBar"></span></div><span id="syncText">Reading current Airtable items…</span>';const map=await existingMap();let done=0,created=0,updated=0;for(let i=0;i<items.length;i+=10){const slice=items.slice(i,i+10),creates=[],updates=[];for(const x of slice){const id=map.get(x.id);if(id)updates.push({id,fields:fields(x)});else creates.push({fields:fields(x)})}if(updates.length){await airtable('',{method:'PATCH',body:JSON.stringify({records:updates,typecast:true})});updated+=updates.length}if(creates.length){const d=await airtable('',{method:'POST',body:JSON.stringify({records:creates,typecast:true})});created+=creates.length;for(let j=0;j<creates.length;j++){const rid=d.records?.[j]?.id,k=slice.find(x=>x.id===creates[j].fields['Item ID']);if(rid&&k)map.set(k.id,rid)}}done+=slice.length;const pct=Math.round(done/items.length*100);const bar=$('syncBar'),txt=$('syncText');if(bar)bar.style.width=pct+'%';if(txt)txt.textContent=`${done.toLocaleString()} / ${items.length.toLocaleString()} items • ${pct}%`;await sleep(230)}msg.innerHTML=`✓ PDF inventory synced. ${created.toLocaleString()} created, ${updated.toLocaleString()} updated. Tap REFRESH on the Dashboard so all Truck/Move lists use the full catalog.`}finally{btn.disabled=false}}
function bind(){document.addEventListener('click',e=>{const open=e.target.closest('[data-screen="catalog"]');if(open)setTimeout(()=>ensureLoaded().catch(()=>{}),0);const card=e.target.closest('.catalogItem');if(card)openItem(card.dataset.id)});$('catalogSearch').addEventListener('input',applyFilter);$('catalogCategory').addEventListener('change',applyFilter);$('catalogMore').onclick=()=>{limit+=120;render()};$('catalogClose').onclick=()=>$('catalogModal').classList.add('hidden');$('catalogModal').onclick=e=>{if(e.target===$('catalogModal'))$('catalogModal').classList.add('hidden')};$('catalogSyncBtn').onclick=()=>syncAll().catch(e=>$('catalogSyncMsg').textContent=e.message)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();